### ISSUE TITLE
Job.status() throw IndicoQueryException which says 

### ISSUE THREAD

**Issue by denglitong** [IndicoDataSolutions/indico-client-java#38]
![image](https://user-images.githubusercontent.com/13757307/144381199-c33ca48d-d842-4de6-b74f-ca311e09bfbd.png)
Job.status() throws `IndicoQueryException: Call for the job result failed`, and my submission status is `COMPLETE`. I use the code from the team example, it there anything I went wrong (some error occur in my pdf file)? or anybody can give a help? thx.

```
07:57:50.429 [main] INFO com.urbancompass.dip.classification.indico.IndicoClassificationServiceWrapperTest -
submission id 359, datasetId 10, status: COMPLETE, workflowId 4,
inputFilename dip-183076ed-24bd-4346-8328-7e0d3fca3d37-1638431578400,
inputFile /storage/uploads/14/205c546c-2dd0-4590-b2cb-acb756eabf6e.pdf,
resultFile /storage/submission/4/359/40ace189-4a6a-40ed-87c7-7f2e496640a9.json, retrieved false
E
Time: 12.274
There was 1 failure:

com.indico.exceptions.IndicoQueryException: Call for the job result failed
	at com.indico.query.Job.fetchResult(Job.kt:71)
	at com.indico.query.Job.status(Job.kt:26)
	at com.urbancompass.dip.classification.indico.IndicoClassificationServiceWrapperTest.testGetDocClassification(IndicoClassificationServiceWrapperTest.java:73)
	... 35 trimmed
Caused by: com.indico.exceptions.IndicoQueryException: JacksonGraphQLError(message=An error occured,
 locations=[JacksonGraphQLSourceLocation(line=4, column=5)], path=[job, result],
 extensions={url=http://apiserver:5000/async/9cfdaf04-7914-4b53-806e-1bec72125f35, content={},
 error_class=ServiceException, error_type=IndicoError, code=400})
	at com.indico.query.Job.fetchResult(Job.kt:64)
```

**Comment by denglitong** [comment]
Sorry for interrupting, need help! @nkassis @goatrocks @acousineau @jklingen92

**Comment by denglitong** [comment]
It seems that some problem with my workflow, and when I change another workflow, it works fine. BTW, the error is hard to understand what happens and it makes me confused.

**Comment by denglitong** [comment]
Well, it seems that the `indico-client-java` has some bugs. And the [example of retrieving results](https://github.com/IndicoDataSolutions/indico-client-java/blob/master/examples/SubmissionExample.java#L81) here doesn't work. the alternative way to make it work is as follows:
```
Blob blob = null;
try {
    // retrieve blob
    String url = "https://beta-indico.xxx.com/" + submission.resultFile;
    RetrieveBlob ret_storage_obj = indicoClient.retrieveBlob();
    ret_storage_obj.url(url);
    blob = ret_storage_obj.execute();
    LOG.info("submission id {} blob result {}", submission.id, blob.asString());
    blob.close();

    // update submission retrieved
    UpdateSubmission update_sub = indicoClient.updateSubmission();
    update_sub.submissionId(submission.id);
    update_sub.retrieved(true);
    update_sub.execute();
} catch (Exception ex) {
    LOG.error("something went wrong", ex);
} finally {
    if (blob != null) {
        blob.close();
    }
}
```
